const PRODUCTS = [
  {
    id: 'loop',
    name: 'Loop',
    category: 'Side Table',
    price: 1200,
    dimensions: '30 x 40 x 50 cm',
    description: 'A tall side table that opens an arch. The void is as important as the steel — presence through negative space. Stands beside any chair or sofa with quiet authority.',
    images: ['images/products/LoopSideTable/1.png', 'images/products/LoopSideTable/2.png', 'images/products/LoopSideTable/3.png'],
  },
  {
    id: 'elephant-dining',
    name: 'Elephant Dining',
    category: 'Dining Table',
    price: 5000,
    dimensions: '120 x 120 x 75 cm',
    description: 'An organic oval surface carried by three cylindrical legs. Inspired by the forms of nature — this dining table feels alive, sculptural yet grounded enough for daily life.',
    images: ['images/products/ElephantDining/1.png', 'images/products/ElephantDining/2.png'],
  },
  {
    id: 'c-table',
    name: 'C-Table',
    category: 'Side Table',
    price: 990,
    dimensions: '35 x 45 x 50 cm',
    description: 'A minimal side companion. The C-form in 201 stainless steel is designed to slide under sofas and beside beds — always close, never in the way.',
    images: ['images/products/C-Table/1.png', 'images/products/C-Table/2.png', 'images/products/C-Table/3.png', 'images/products/C-Table/4.png'],
  },
  {
    id: 'ripple',
    name: 'Ripple Stool',
    category: 'Stool',
    price: 450,
    dimensions: '37 x 32 x 48 cm',
    description: 'Parallel wires trace a continuous loop, creating a stool from a single rhythmic gesture. Chrome wire steel, light and layered — sculpture you can sit on.',
    images: ['images/products/RippleStool/1.png', 'images/products/RippleStool/2.png'],
  },
  {
    id: 'nordic',
    name: 'Nordic',
    category: 'Nesting Tables',
    price: 1100,
    dimensions: '35 x 45 x 45 cm',
    description: 'Two nesting forms echo the same gesture at different scales. Brushed steel tables that stack inside each other — expanding or compacting your living space as needed.',
    images: ['images/products/Nordic/1.png', 'images/products/Nordic/2.png', 'images/products/Nordic/3.png'],
  },
  {
    id: 'three-level',
    name: 'Three Level',
    category: 'Coffee Table',
    price: 1900,
    dimensions: '70 x 70 x 47 cm',
    description: 'Geometric circles and rectangles interlock at different heights — architecture in miniature. A coffee table that works as display surface, side table, and sculptural object.',
    images: ['images/products/ThreeLevel/1.png', 'images/products/ThreeLevel/2.png'],
  },
  {
    id: 'plie',
    name: 'Plié',
    category: 'Coffee Table',
    price: 2700,
    dimensions: '50 x 90 x 44 cm',
    description: 'Named after the ballet movement. The surface folds into vertical legs without seam or visible weld — one continuous gesture in steel, lowered to the ground.',
    images: ['images/products/PLIE/1.png', 'images/products/PLIE/2.png', 'images/products/PLIE/3.png', 'images/products/PLIE/4.png'],
  },
  {
    id: 'elephant-low',
    name: 'Elephant Low',
    category: 'Coffee Table',
    price: 2500,
    dimensions: '85 x 85 x 42 cm',
    description: 'The Elephant form, lowered to the ground. An organic coffee table with quiet, monumental presence — its oval surface hovering above three cylindrical columns.',
    images: ['images/products/ElephantLowTable/1.png'],
  },
  {
    id: 'rectangular-s',
    name: 'Rectangular S',
    category: 'Living Room Table',
    price: 2300,
    dimensions: '60 x 100 x 42 cm ',
    description: 'The simplest gesture: a rectangle that folds into legs. Brushed steel flows from surface to floor without interruption — pure form, zero ornament.',
    images: ['images/products/RectangularLivingRoom/1.png', 'images/products/RectangularLivingRoom/2.png'],
  },
  {
    id: 'rectangular-l-',
    name: 'Rectangular L',
    category: 'Living Room Table',
    price: 2500,
    dimensions: '60 x 120 x 42 cm',
    description: 'The simplest gesture: a rectangle that folds into legs. Brushed steel flows from surface to floor without interruption — pure form, zero ornament.',
    images: ['images/products/RectangularLivingRoom/1.png', 'images/products/RectangularLivingRoom/2.png'],
  },
];
