const PRODUCTS = [
  {
    id: 'loop',
    name: 'Loop',
    category: 'Side Table',
    price: 1,
    discount: 0,
    dimensions: '30 x 40 x 50 cm',
    description: 'שולחן Loop בעיצוב מינימליסטי וייחודי שמתאים לכל מקום בבית. בזכות המראה הנקי והמבריק שלו, הוא משדרג בקלות כל חלל ומשלב בין סטייל לפרקטיקה. רב-שימושי: מתאים כשולחן צד לסלון, שולחן קפה קטן או כשידת לילה מעוצבת ליד המיטה. עשוי נירוסטה איכותית עם ליטוש ידני למראה יוקרתי ועמידות לאורך זמן.',
    images: ['/images/products/LoopSideTable/1.png', '/images/products/LoopSideTable/2.png', '/images/products/LoopSideTable/3.png'],
  },
  {
    id: 'elephant-dining',
    name: 'Elephant Dining',
    category: 'Dining Table',
    price: 5000,
    discount: 0,
    dimensions: '120 x 120 x 75 cm',
    description: 'שולחן אוכל Elephant Leg הוא הצהרה עיצובית יוצאת דופן. השולחן מציג נוכחות מרשימה, המשלבת בין חומריות תעשייתית לבין קווים גיאומטריים מתוחכמים. השולחן מתאים לאירוח של 5-7 סועדים, עשוי נירוסטה איכותית בגימור מלוטש ויוקרתי. המבנה שלו מדגיש את היופי הגולמי של המתכת תוך שמירה על מראה נקי, מודרני וקליל באופן מפתיע.',
    images: ['/images/products/ElephantDining/1.png', '/images/products/ElephantDining/2.png'],
  },
  {
    id: 'c-table',
    name: 'C-Table',
    category: 'Side Table',
    price: 990,
    discount: 0,
    dimensions: '35 x 45 x 50 cm',
    description: 'נשכן עשוי 100% נירוסטה מרשים, מלא בסטייל, נקי, קלאסי ויוקרתי, ניתן לשימוש גם בתור שולחן צד',
    images: ['/images/products/C-Table/1.png', '/images/products/C-Table/2.png', '/images/products/C-Table/3.png', '/images/products/C-Table/4.png'],
  },
  {
    id: 'ripple',
    name: 'Ripple Stool',
    category: 'Stool',
    price: 450,
    discount: 0,
    dimensions: '37 x 32 x 48 cm',
    description: 'Parallel wires trace a continuous loop, creating a stool from a single rhythmic gesture. Chrome wire steel, light and layered — sculpture you can sit on.',
    images: ['/images/products/RippleStool/1.png', '/images/products/RippleStool/2.png'],
  },
  {
    id: 'nordic',
    name: 'Nordic',
    category: 'Nesting Tables',
    price: 1100,
    discount: 0,
    dimensions: '35 x 45 x 45 cm',
    description: 'Two nesting forms echo the same gesture at different scales. Brushed steel tables that stack inside each other — expanding or compacting your living space as needed.',
    images: ['/images/products/Nordic/1.png', '/images/products/Nordic/2.png', '/images/products/Nordic/3.png'],
  },
  {
    id: 'three-level',
    name: 'Three Level',
    category: 'Coffee Table',
    price: 1900,
    discount: 0,
    dimensions: '70 x 70 x 47 cm',
    description: 'Geometric circles and rectangles interlock at different heights — architecture in miniature. A coffee table that works as display surface, side table, and sculptural object.',
    images: ['/images/products/ThreeLevel/1.png', '/images/products/ThreeLevel/2.png'],
  },
  {
    id: 'plie',
    name: 'Plié',
    category: 'Coffee Table',
    price: 2700,
    discount: 0,
    dimensions: '50 x 90 x 44 cm',
    description: 'Named after the ballet movement. The surface folds into vertical legs without seam or visible weld — one continuous gesture in steel, lowered to the ground.',
    images: ['/images/products/PLIE/1.png', '/images/products/PLIE/2.png', '/images/products/PLIE/3.png', '/images/products/PLIE/4.png'],
  },
  {
    id: 'elephant-low',
    name: 'Elephant Low',
    category: 'Coffee Table',
    price: 2500,
    discount: 0,
    dimensions: '85 x 85 x 42 cm',
    description: 'The Elephant form, lowered to the ground. An organic coffee table with quiet, monumental presence — its oval surface hovering above three cylindrical columns.',
    images: ['/images/products/ElephantLowTable/1.png'],
  },
  {
    id: 'rectangular-s',
    name: 'Rectangular S',
    category: 'Living Room Table',
    price: 2300,
    discount: 0,
    dimensions: '60 x 100 x 42 cm ',
    description: 'The simplest gesture: a rectangle that folds into legs. Brushed steel flows from surface to floor without interruption — pure form, zero ornament.',
    images: ['/images/products/RectangularLivingRoom/1.png', '/images/products/RectangularLivingRoom/2.png'],
  },
  {
    id: 'magazine-rack-curves',
    name: 'Magazine Rack Curves',
    category: 'STOOL',
    price: 450,
    discount: 0,
    dimensions: '30 x 46 x 37 cm',
    description: '',
    images: ['/images/products/MagazineRackCurves/1.png', '/images/products/MagazineRackCurves/2.png'],
  },
  {
    id: 'river-box-table',
    name: 'River Box Table',
    category: 'Side Table',
    price: 1200,
    discount: 0,
    dimensions: '',
    description: '',
    images: ['/images/products/RiverBoxTable/1.png', '/images/products/RiverBoxTable/2.png'],
  },
  {
    id: 'rectangular-l',
    name: 'Rectangular L',
    category: 'Living Room Table',
    price: 2500,
    discount: 0,
    dimensions: '60 x 120 x 42 cm',
    description: '',
    images: ['/images/products/RectangularLivingRoom/1.png', '/images/products/RectangularLivingRoom/2.png'],
  },
];
